# Site settings
title: Yuxi Liu
email: yuxi.liu.1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an honours student of mathematics at Australian National University.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yuxi-liu-1995.github.io" # the base hostname & protocol for your site
# permalink: /blog/:year/:month/:title.html

# Google Analytics
google_analytics: UA-139427416-1

show_last_update: true

gems:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll/scholar

# Build settings
markdown: kramdown
theme: minima
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    twitter: 1995Yuxi
    github:  yuxiliu1995
    # rss: rss
    # linkedin: jekyll
show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - publications.md
 - notes.md
 - corrections.md
# NOT WORKING

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# For bibtex
scholar:
  style: chicago-author-date
  locale: en

  sort_by: author,year,month
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: default.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
# For laTeX
kramdown:
   math_engine: mathjax
