# Site settings
title: Yuxi Liu
email: yuxi.liu.1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an honours student at Australian National University.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yuxi-liu-1995.github.io" # the base hostname & protocol for your site
twitter_username: 1995Yuxi
github_username:  yuxi-liu-1995
# permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima

# For bibtex
gems: ['jekyll/scholar']

scholar:
  style: chicago-author-date
  locale: en

  sort_by: author,year,month
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: default.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# For laTeX
kramdown:
   math_engine: mathjax
